[deepseek]
api_key = "sk-240dea85c5b54dbbaf7e12793fdf6741"
model = "deepseek-reasoner"

[retrieval]
search_provider = "duckduckgo"
tavily_api_key = "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"

[storage]
persist_directory = "./.chromadb"

[app]
locale = "auto"
default_language = "auto"

[langsmith]
enabled = true
api_key = "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"
api_url = "https://api.smith.langchain.com"
project = "FakeScope"
